### ISSUE TITLE
Package as an action/separate codebase from generated images

### ISSUE THREAD

**Issue by chris48s** [jstrieb/github-stats#6]
At the moment this project has potential, but the suggested install process is a bit clunky because when I fork it, the code comes with your generated images. As soon as a user starts generating their own images and the histories diverge, it then it becomes potentially fiddly to pull in any changes or bugfixes from upstream into the forks.

If the action code were decoupled from your generated image history in a separate repo with an `action.yml` the "install" process for a new user could be more like: Create an empty repo and create a workflow:

```yml
name: Generate Images
on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Images
        uses: jstrieb/github-stats@master
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          EXCLUDED: ${{ secrets.EXCLUDED }}
```

which would be much slicker as each user repo would only contain the user's own image history.
