### ISSUE TITLE
Overflow problem !

### ISSUE THREAD

**Issue by NazmusSayad** [jstrieb/github-stats#71]
In small width devices some content of language.svg is overflowing. I was trying to fix it and if found the bug.

# Problem:
```css
foreignObject {
  width: calc(100% - 10px - 32px);
  height: calc(100% - 10px - 24px);
}
```
![vivo-v5s-5 5-720 x 1280](https://user-images.githubusercontent.com/87106526/171375079-7b31dc68-7bcf-4982-b197-881af7116125.png)

# Fix:
But without the height and width property everything is fine.
```css
foreignObject {
}
```
![dddd](https://user-images.githubusercontent.com/87106526/171376167-4ad3105e-6a44-4a37-901b-b3c3d2c239a0.png)
