### ISSUE TITLE
No name's github stats

### ISSUE THREAD

**Issue by reveurguy** [jstrieb/github-stats#77]
I am trying to implement the stats on readme. I have created all the files and folders and yaml file but I am getting No name's github stats and no stats. I am an attaching the image for reference:

<img width="374" alt="Screenshot 2022-07-06 at 2 58 34 PM" src="https://user-images.githubusercontent.com/59417546/177518612-46703ed8-82c4-4050-a5d2-f5bfe7f3a764.png">

This is my main.yml file:

```
# This is a basic workflow to help you get started with Actions

name: Generate Stats Images

# Controls when the action will run. Triggers the workflow on push events
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    # Cache dependencies. From:
    # https://github.com/actions/cache/blob/master/examples.md#python---pip
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-


    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        EXCLUDE_FORKED_REPOS: true

    # Commits all changed files to the repository
    - name: Commit to the output branch of repo
      run: |
        git config --global user.name "reveurguy"
        git config --global user.email "reveur.guy99@gmail.com"
        git add .
        git commit -m 'temp commit' || echo
        git checkout output1 2>/dev/null || git checkout --orphan output1 && git rm -rf . && git checkout master -- generated/
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'Update generated files' || echo
        git push origin output1 -f
```
